### ISSUE TITLE
"This power related thing is messed up" master issue

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#82196]
Notice something related to power or cells is messed up? Add here if not listed. 

Definitely affected:
- [ ] Sec batons / Secborg batons
- [x] Cyborg Electroadaptive Pseudocircuit (thing engiborgs use to make circuits)
- [x] Cyborg RCD
- [x] Cyborg self repair
- [x] Cyborg lollipop dispenser
- [ ] Cyborg stun arm
- [ ] Cyborg energy sword
- [x] Cyborg hypospray
- [x] Cyborg projectile dampener
- [x] Cyborg chameleon (sabo borgs)
- [x] Defib EMP (actual revival is fine) 
- [x] Cell EMP
- [x] EVA temp regulators (#82195)
- [x] Firelance (admin only / unused anyways) 
- [x] Microwaves (see `TIER_1_CELL_CHARGE_RATE`)
- [x] Botany potato batteries
- [ ] Botany cell charging
- [x] Mauna mug
- [ ] Plasma cutter (recharging was scaled, but not charge use) 
- [x] Whatever `/datum/action/cooldown/mob_cooldown/charge_apc` is
- [ ] BCIs, to some degree (`on_electrocute`?)
- [x] Motorized Wheelchairs
- [x] MOD links
- [x] Light fixtures (see `LIGHT_EMERGENCY_POWER_USE` too)
- [x] Mecha weapons / tools (see equipment `energy_drain`, also see anything that uses `use_energy`, IE mecha RCD)

Maybe affected, needs double checking:
- [x] Canister shielding
- [ ] Mecha power gens
- [x] Space heaters
- [x] Electrolyzers
- [ ] `electrocute_mob`

Also maybe of note, I think they're fine effectively but may need tweaks:
- [ ] Non- [ ]standard MOD cores
- [x] Ninja drain
- [x] Mod PC power usage

**Comment by Deadgebert** [comment]
crank weapons weapons such as thermal pistols and smoothbore generate significantly less energy than is required for a shot. 1/1000th in the case of thermal pistol

**Comment by SyncIt21** [comment]
Actually doesn't everything need to be changed?

`use_energy()` fill first attempt to use power from the apc cell(unless `grid_only = TRUE`) and if `force = TRUE` it will draw power from the grid. Since apc cells were scaled up all cases of `use_energy()` should also be scaled up as well?

@Pickle-Coding did i understand this correctly?

**Comment by necromanceranne** [comment]
I've certainly encountered APC draw appearing to be fairly intense in places where the power used to run fairly decently long with no issue. The lavaland mining base, for example, appears to run its battery out of equipment functionality in 15 minutes, stranding the miners on lavaland before their first back if they're not immediately back before the first storm, and the shuttle isn't on lavaland. This affects both public and departmental.

**Comment by Pickle-Coding** [comment]
> Actually doesn't everything need to be changed?
> 
> 
> 
> `use_energy()` will first attempt to use power from the apc cell(unless `grid_only = TRUE`) and if `force = TRUE` it will draw power from the grid(for the remaining left over load if the apc cell could not satisfy it). Since apc cells were scaled up all cases of `use_energy()` should also be scaled up as well?
> 
> 
> 
> @Pickle-Coding did i understand this correctly?

use_energy() prioritises the grid first before attempting to use the cell. The problem is processing priority. Apparantly telecomms machinery are on the later end of the processing order, and they don't get to use any surplus from roundstart power, so all of that ~25kW consumption is using the cell.

In an ideal world, processing order wouldn't matter and grid usage would be composition based, but I don't know how to do that in a sane way while also ensuring we can't duplicate energy or unnecessarily delete energy.

We could give telecomms APC a better cell to last longer maybe, or we could sort the processing order of machines based on their area's power usage from last tick and process ones in high power usage first.

**Comment by Pickle-Coding** [comment]
> I've certainly encountered APC draw appearing to be fairly intense in places where the power used to run fairly decently long with no issue. The lavaland mining base, for example, appears to run its battery out of equipment functionality in 15 minutes, stranding the miners on lavaland before their first back if they're not immediately back before the first storm, and the shuttle isn't on lavaland. This affects both public and departmental.

I guess I could give it more pacmans or something. Maybe it could run a turbine. I don't exactly know the cause for lavaland power issues. Maybe I'll look into it deeper.

**Comment by Pickle-Coding** [comment]
Okay it seems like the lavaland APCs only start at 10% roundstart. Maybe I forgot to convert their starting energy.

**Comment by Pickle-Coding** [comment]
Oh, of course there are var edited SMES littered around.

**Comment by Pickle-Coding** [comment]
I just remembered that telecomms uses an SMES. I think the power issue there is a consequence of low SMES charge and not processing order, so hopefully fixing the SMES issue fixes that.

**Comment by SyncIt21** [comment]
> Cyborg RCD

> Botany potato batteries

You can check this out to. Addressed in part 1

>  Light fixtures (see LIGHT_EMERGENCY_POWER_USE too)

Addressed in part 3. Lights do use are energy for normal cases and its emergency usage has been addressed

**Comment by MrMelbert** [comment]
> > Light fixtures (see LIGHT_EMERGENCY_POWER_USE too)
> 
> Addressed in part 3. Lights use area energy for normal cases and its emergency usage has been fixed

Light fixture `power_consumption_rate` seems untouched though. Or am I misunderstanding?

**Comment by SyncIt21** [comment]
> Light fixture power_consumption_rate seems untouched though. Or am I misunderstanding?

Thats for area static power usage. It does not use cell power

**Comment by lessthnthree** [comment]
Space heater has a for loop where it heats tiles and uses cell. It calculates the cell required to heat each tile but performs cell.use outside the loop, only using cell power once regardless of how many tiles are heated.

**Comment by TagGamerGang22** [comment]
The SMES issue appears to affect the AI sat SMES as well.

**Comment by DaydreamIQ** [comment]
Unsure If it's already been addressed or not but it seems that recharging power cells acts as a local powersink for whatever reason

**Comment by Pickle-Coding** [comment]
> Unsure If it's already been addressed or not but it seems that recharging power cells acts as a local powersink for whatever reason

Intentional to conserve energy.

**Comment by DaydreamIQ** [comment]
> > Unsure If it's already been addressed or not but it seems that recharging power cells acts as a local powersink for whatever reason
> 
> Intentional to conserve energy.

Its intentional that trying to charge a single cell blacks out the entire room???

**Comment by necromanceranne** [comment]
I thought cell chargers are pulled from the grid to prevent them draining APCs, not the other way around. This was a problem a few years ago.

**Comment by Pickle-Coding** [comment]
The alternative would be causing a station wide powersink that would fuck every department that had a somewhat high power consumption until the powercell gets fully charged.

If engineers put enough power into the grid, then it won't be as bad. I also made APCs much more responsive and reactive to losing energy, so they immediately begin recharging.

**Comment by lessthnthree** [comment]
Mod PC power usage: https://github.com/tgstation/tgstation/pull/82254

**Comment by LemonInTheDark** [comment]
> > Unsure If it's already been addressed or not but it seems that recharging power cells acts as a local powersink for whatever reason
> 
> Intentional to conserve energy.

the solution to this problem is a new part that goes in APCs and SMES that's for storing power in APCs/SMESs

**Comment by LemonInTheDark** [comment]
Yeah. the issue is the conversion factor between charging a cell outside an apc and using it to power an apc right?

**Comment by Pickle-Coding** [comment]
> Yeah. the issue is the conversion factor between charging a cell outside an apc and using it to power an apc right?

I suppose so. APCs by default only use the upgraded cell (2.5MJ), while everyone and their mom uses high capacity power cells at minimum (10MJ) for pretty much everything. Seems kinda backwards logic.

It's worth noting that APC cells contribute a significant portion to the roundstart energy supply, so changing that will have a large impact on the time it takes to run out of power. I'll have to approach this carefully.

**Comment by SyncIt21** [comment]
@MrMelbert Please update the task list.

**Comment by Iajret** [comment]
> > Unsure If it's already been addressed or not but it seems that recharging power cells acts as a local powersink for whatever reason
> 
> Intentional to conserve energy.

It is and it isn't. Every physics adept will say that 40 MJ is insane amount of energy, and even "mere" 1 MW of power will take 40 secs to charge a single cell. But you need to have this much power available in the powernet. A whole 1 MW for each cell charger, just in case somehow someone decides to use more than a single one. Upgraded station with working hydro, chem factory and HFR consumed just a bit more than 1 MW. And now you need to supply this much power for 40 seconds every time the cell is charged?

**Comment by SyncIt21** [comment]
Please update the task list.

**Comment by iprice** [comment]
Seems possibly issues with the borg inducer still using a hard coded value, probably also the syndie inducer.

Borg/modsuit charging stations seem very slow for recharging borgs ; we attempted to increase the charge rate on the borg charger and it had no effect, another admin noted that cells have max charge rates and when we increased this too the borg started /discharging/ its cell while in the borg charger (??)  Both values were just multiplied by 100-1000

**Comment by Y0SH1M4S73R** [comment]
Machine chaplains get way too much favor from power cells.

**Comment by OverwatchVoice** [comment]
Unsure if related, but [space heaters drain charge stupidly quick](https://github.com/tgstation/tgstation/issues/84440).

**Comment by Sadboysuss** [comment]
I think this can be closed now?

**Comment by Bibarra** [comment]
Inducers only charge like, 2% of APC.

**Comment by Sadboysuss** [comment]
> Inducers only charge like, 2% of APC.

https://github.com/user-attachments/assets/a1ae7224-94ae-4128-b803-39f174a2a45f

https://github.com/user-attachments/assets/e9cf3d3f-bda8-4379-8859-f836c7418909

Looks like inducers charge a set amount of power: 1 mj per "charging tick", which would make any inducer, when trying to charge a bluespace megacell for example: charge it by 2.5% (100/(40MJ/1MJ)), but a high capacity megacell would be charged by 10% every "charging tick" since it's (100/(10MJ/1MJ)

**Comment by Sadboysuss** [comment]
we have a power consumption fixes milestone now and most of these issues are fixed now. any new issues regarding power consumption should be made as their own issues now.
